# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_lvl', models.IntegerField(default=0, verbose_name='Первый уровень')),
                ('two_lvl', models.IntegerField(default=0, verbose_name='Второй уровень')),
                ('three_lvl', models.IntegerField(default=0, verbose_name='Третий уровень')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'db_table': 'referal',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0, verbose_name='Телефон')),
                ('nick', models.CharField(max_length=20, verbose_name='Имя')),
                ('work', models.CharField(blank=True, choices=[('NOS', 'Нет основного места работы'), ('SCHOOL', 'Учусь в школе'), ('STUDENT', 'Студент'), ('PRED', 'Предприниматель'), ('WORKSPRED', 'Работник на предприятии'), ('SLUG', 'Служащий на предприятии')], default='Выбор', max_length=30, verbose_name='Род деятельности')),
                ('family', models.CharField(blank=True, choices=[('MARRIED', 'Женат\\замужем, есть дети'), ('MARRIEDS', 'Женат\\замужем, нет детей'), ('NOMARRIED', 'Не женат\\Не замужем, есть дети'), ('NOMARRIEDS', 'Не женат\\Не замужем, нет детей'), ('DIVORCED', 'Разведен\\разведена, есть дети'), ('DIVORCEDS', 'Разведен\\разведена, нет детей')], default='Выбор', max_length=30, verbose_name='Семейное положение')),
                ('sex', models.CharField(blank=True, choices=[('MEN', 'Мужчина'), ('WOOMEN', 'Женщина')], default='Выбор', max_length=30, verbose_name='Пол')),
                ('birth', models.DateField(default='1970-01-01', verbose_name='Дата рождения')),
                ('wmr', models.CharField(blank=True, default=0, max_length=20, verbose_name='Номер счёта WMR (Вместе с латинской R)')),
                ('yandex', models.CharField(blank=True, default=0, max_length=20, verbose_name='Yandex кошелек')),
                ('qiwi', models.CharField(blank=True, default=0, max_length=20, verbose_name='QIWI кошелек')),
                ('payeer', models.CharField(blank=True, default=0, max_length=20, verbose_name='Payeer (Вместе с латинской P)')),
                ('perfect_money', models.CharField(blank=True, default=0, max_length=20, verbose_name='Perfect Money (Вместе с латинской U)')),
                ('schet_lich', models.FloatField(blank=True, default=0)),
                ('schet_reklam', models.FloatField(blank=True, default=0)),
                ('refery', models.IntegerField(blank=True, default=0, verbose_name='Рефери')),
                ('rating', models.FloatField(blank=True, default=0, verbose_name='Рейтинг')),
                ('status', models.CharField(default='Новичок', max_length=20, verbose_name='Статус')),
                ('website', models.URLField(blank=True, verbose_name='Мой сайт')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images', verbose_name='Фотография')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='UserPopoln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.FloatField(default=0, verbose_name='Сумма')),
                ('sys', models.CharField(max_length=20, verbose_name='Кошелек')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('odobren', models.BooleanField(default=False, verbose_name='Успех пополнения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
                'db_table': 'popoln_user',
            },
        ),
        migrations.CreateModel(
            name='Viplati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(default=0, verbose_name='Сумма')),
                ('sys_viplat', models.CharField(max_length=20, verbose_name='Система для выплаты')),
                ('ub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобрин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Заказы выплат',
                'db_table': 'viplati_user',
            },
        ),
    ]
