# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.date(2017, 3, 15), verbose_name='Дата последнего входа')),
                ('serf', models.IntegerField(blank=True, default=0, verbose_name='Серфинг')),
                ('task', models.IntegerField(blank=True, default=0, verbose_name='Задания')),
                ('test', models.IntegerField(blank=True, default=0, verbose_name='Тесты')),
                ('pismo', models.IntegerField(blank=True, default=0, verbose_name='Письма')),
                ('viplat', models.FloatField(blank=True, default=0, verbose_name='Всего выплат')),
                ('ref_one', models.FloatField(blank=True, default=0, verbose_name='Заработано с рефералов 1 ур.')),
                ('ref_two', models.FloatField(blank=True, default=0, verbose_name='Заработано с рефералов 2 ур.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ститистика пользователей',
                'db_table': 'user_static',
                'verbose_name': 'Ститистика пользователя',
            },
        ),
    ]
