# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistica',
            name='activ_user',
            field=models.IntegerField(default=0, verbose_name='Активных пользователей'),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='click',
            field=models.IntegerField(default=0, verbose_name='Клики'),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='task',
            field=models.IntegerField(default=0, verbose_name='Задания'),
        ),
        migrations.AlterField(
            model_name='statistica',
            name='viplat',
            field=models.IntegerField(default=0, verbose_name='Выплаты'),
        ),
    ]
