# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statis', '0002_auto_20170121_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistica',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
