# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billtest', '0002_auto_20170122_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billtest',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='billtest',
            name='poage',
        ),
        migrations.RemoveField(
            model_name='billtest',
            name='pofamaly',
        ),
        migrations.RemoveField(
            model_name='billtest',
            name='porod',
        ),
        migrations.RemoveField(
            model_name='billtest',
            name='posex',
        ),
        migrations.RemoveField(
            model_name='billtest',
            name='vid_t',
        ),
        migrations.AddField(
            model_name='billtest',
            name='odobren',
            field=models.BooleanField(default=False, verbose_name='Одобраить'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='price',
            field=models.FloatField(default=0.4, verbose_name='Вознаграждение исполнителю'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='price_test',
            field=models.FloatField(default=10.0, verbose_name='Укажите сумму баланса задания'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='url_admin',
            field=models.URLField(blank=True, verbose_name='Укажите, (URL) вы представляете в задании. (максимум 200 символов)'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='pravila',
            field=models.BooleanField(default=True, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE'),
        ),
    ]
