# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billtest', '0004_auto_20170123_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtest',
            name='var_one',
            field=models.IntegerField(default=1, verbose_name='Укажите номер ответа на вопрос №1'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='var_three',
            field=models.IntegerField(default=1, verbose_name='Укажите номер ответа на вопрос №3'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='var_two',
            field=models.IntegerField(default=1, verbose_name='Укажите номер ответа на вопрос №2'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_1_ans_1',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №1'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_1_ans_2',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №2'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_1_ans_3',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №3'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_2_ans_1',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №1'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_2_ans_2',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №2'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_2_ans_3',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №3'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_3_ans_1',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №1'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_3_ans_2',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №2'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='quest_3_ans_3',
            field=models.CharField(max_length=30, verbose_name='Вариант ответа №3'),
        ),
    ]
