# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billtest', '0005_auto_20170123_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='billtest',
            name='com',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Коментарий модерации'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='moder',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='pausa',
            field=models.BooleanField(default=False, verbose_name='Пауза'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='price_s',
            field=models.FloatField(default=0, verbose_name='Вознограждение сайту'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='price_t',
            field=models.FloatField(default=0, verbose_name='Списание с баланса теста'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='price_u',
            field=models.FloatField(default=0, verbose_name='Вознограждение пользователю'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='prosm',
            field=models.IntegerField(default=0, verbose_name='Количество выполнений'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='prosm_ost',
            field=models.IntegerField(default=0, verbose_name='Количество выполнений осталось'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='spis',
            field=models.BooleanField(default=False, verbose_name='Списание с 11р.'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='sum_spis',
            field=models.IntegerField(default=0, verbose_name='Сумма для списания'),
        ),
        migrations.AddField(
            model_name='billtest',
            name='vid_t',
            field=models.CharField(choices=[('ONE_T', 'Нет'), ('TWO_T', 'Выделить тест среди других + 0.02 руб.')], default='Выбор', max_length=30, verbose_name='Выделить тест среди других'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='price_test',
            field=models.FloatField(default=0, verbose_name='Укажите сумму баланса теста'),
        ),
        migrations.AlterField(
            model_name='billtest',
            name='time_t',
            field=models.CharField(choices=[('ONE_T', 'Доступно всем каждые 24 часа'), ('TWO_T', '30 секунд + 0.15 руб.')], default='Выбор', max_length=30, verbose_name='Технология тестирования'),
        ),
    ]
