# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170112_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelTable(
            name='post',
            table='news',
        ),
    ]
