# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksusers',
            name='proverka',
            field=models.BooleanField(default=False, verbose_name='Проверка'),
        ),
    ]
