# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasksusers_proverka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksa',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='tasksusers',
            options={'verbose_name': 'Ответ на задания', 'verbose_name_plural': 'Ответы на задания'},
        ),
    ]
