# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170123_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksa',
            name='posex',
            field=models.CharField(choices=[('VSE', 'Все пользователи'), ('MEN_SEX', 'Мужчина'), ('WOOMEN_SEX', 'Женщина')], default='Выбор', max_length=10, verbose_name='По половому признаку'),
        ),
    ]
