# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20170217_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksa',
            name='com',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Коментарий модерации'),
        ),
        migrations.AddField(
            model_name='tasksa',
            name='pausa',
            field=models.BooleanField(default=False, verbose_name='Пауза'),
        ),
        migrations.AlterField(
            model_name='tasksusers',
            name='start_task',
            field=models.DateTimeField(verbose_name='Время на выполнение'),
        ),
    ]
