# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок ссылки')),
                ('website', models.URLField(blank=True, verbose_name='URL сайта (включая http://)')),
                ('dop', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да (+5.00 руб.)')], default='Выбор', max_length=30, verbose_name='Выделить ссылку')),
                ('pravila', models.BooleanField(default=False, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
