# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsite',
            name='odobren',
            field=models.BooleanField(default=False, verbose_name='Одобраить'),
        ),
    ]
