# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogsite_odobren'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogsite',
            name='price',
            field=models.IntegerField(default=20),
        ),
    ]
