# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogsite_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsite',
            name='price',
            field=models.FloatField(default=20.0),
        ),
    ]
