# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170112_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsite',
            name='website',
            field=models.URLField(verbose_name='URL сайта (включая http://)'),
        ),
    ]
