# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170121_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogsite',
            options={'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталог сайтов'},
        ),
    ]
