# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:19
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasksa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('opisan', ckeditor.fields.RichTextField(max_length=2000)),
                ('opis_vipoln', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('url_admin', models.URLField()),
                ('url', models.URLField(blank=True)),
                ('price', models.FloatField(default=0.1)),
                ('tech', models.CharField(choices=[('ONE', 'Один пользователь - одно выполнение'), ('MNOGO', 'Задание можно выполнять многократно')], default='Выбор', max_length=30, verbose_name='Технология выполнения задания')),
                ('srock', models.CharField(choices=[('one_h', '1 час'), ('two_h', '2 часа'), ('six_h', '6 часов'), ('tvel_h', '12 часов'), ('one_d', '1 день'), ('two_d', '2 дня'), ('three_d', '3 дня'), ('five_d', '5 дней')], default='Выбор', max_length=10, verbose_name='Максимальный срок, отведённый на выполнение задания')),
                ('interval', models.CharField(choices=[('BEZ', 'Без интервала'), ('ONE_M', '1 минута'), ('TWO_M', '2 минуты'), ('FIVE_M', '5 минут'), ('TEN_M', '10 минут'), ('TWENTY_M', '20 минут'), ('THIRTY_M', '30 минут'), ('ONE_H', '1 час'), ('TWO_H', '2 часа'), ('SIX_H', '6 часов'), ('TVEL_H', '12 часов'), ('TWNTYF_H', '24 часа')], default='Выбор', max_length=10, verbose_name='Минимальный интервал очереди последовательной раздачи заданий')),
                ('audit', models.CharField(choices=[('VSE', 'Все пользователи'), ('IZBRAN', 'Только исполнители из списка избарнных')], default='Выбор', max_length=10, verbose_name='Аудитория исполнителей')),
                ('porefer', models.CharField(choices=[('VSEP', 'Все пользователи'), ('BEZREFER', 'Только пользователи без реферала'), ('MOIREFER', 'Только мой рефералы')], default='Выбор', max_length=10, verbose_name='По наличию реферера')),
                ('porating', models.CharField(choices=[('VSEP', 'Все пользователи'), ('BEZREFER', 'Только пользователи без реферала'), ('MOIREFER', 'Только мой рефералы')], default='Выбор', max_length=10, verbose_name='По рейтингу серфера')),
                ('porep', models.CharField(choices=[('VSEPOLZ', 'Все пользователи'), ('ZERO_REP', 'С репутацией от 0 и выше'), ('ONE_REP', 'С репутацией от 1 и выше'), ('FIVE_REP', 'С репутацией от 5 и выше'), ('TEN_REP', 'С репутацией от 10 и выше'), ('TWENTY_REP', 'С репутацией от 20 и выше'), ('THIRTY_REP', 'С репутацией от 30 и выше'), ('FIVETY_REP', 'С репутацией от 50 и выше'), ('ONEH_R', 'С репутацией от 100 и выше')], default='Выбор', max_length=10, verbose_name='По репутации исполнителя заданий')),
                ('pomet', models.CharField(choices=[('VSEPOLZOV', 'Все пользователи'), ('UCH', 'Учится в школе'), ('STUDENT', 'Студент'), ('PRED', 'Предприниматель'), ('RAB_P', 'Работники на предприятиях'), ('SLUG_P', 'Служащие на предприятиях'), ('BOMR', 'Без основного места работы')], default='Выбор', max_length=10, verbose_name='По репутации исполнителя заданий')),
                ('pofamaly', models.CharField(choices=[('MARRIED', 'Женат\\замужем, есть дети'), ('MARRIEDS', 'Женат\\замужем, нет детей'), ('NOMARRIED', 'Не женат\\Не замужем, есть дети'), ('NOMARRIEDS', 'Не женат\\Не замужем, нет детей'), ('DIVORCED', 'Разведен\\разведена, есть дети'), ('DIVORCEDS', 'Разведен\\разведена, нет детей')], default='Выбор', max_length=10, verbose_name='По семейному положению')),
                ('posex', models.CharField(choices=[('MEN_SEX', 'Мужчина'), ('WOOMEN_SEX', 'Женщина')], default='Выбор', max_length=10, verbose_name='По половому признаку')),
                ('poage', models.CharField(choices=[('LUB_AGE', 'Любой возраст'), ('SIXT_AGE', 'От 16 до 18'), ('EIGHT_AGE', 'От 18 до 20'), ('TWENT_AGE', 'От 20 до 25'), ('TWENTF_AGE', 'От 25 до 30'), ('THIRT_AGE', 'От 30 до 40'), ('FORTY_AGE', 'От 40 до 50'), ('FIVETY_AGE', 'От 50 до 70')], default='Выбор', max_length=10, verbose_name='По возрасту')),
                ('pravila', models.BooleanField(default=False, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='TasksUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_vipoln', models.CharField(max_length=2000)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasksa')),
            ],
        ),
    ]
