# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 00:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksa',
            name='opis_vipoln',
            field=models.CharField(max_length=2000, verbose_name='Что должен указать исполнитель для проверки выполнения задания'),
        ),
        migrations.AlterField(
            model_name='tasksa',
            name='opisan',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Описание задания'),
        ),
        migrations.AlterField(
            model_name='tasksa',
            name='price',
            field=models.FloatField(default=0.1, verbose_name='Вознаграждение исполнителю'),
        ),
        migrations.AlterField(
            model_name='tasksa',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок задания'),
        ),
        migrations.AlterField(
            model_name='tasksa',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL сайта (включая http://)Не обязательно'),
        ),
        migrations.AlterField(
            model_name='tasksa',
            name='url_admin',
            field=models.URLField(verbose_name='Дополнительная информация для арбитров: Укажите, какой ресурс (URL) вы \t\t\t\t\t\tпредставляете в задании. Информация будет видна только вам и \tарбитрам \t\t\t\t\t(максимум 200 символов)'),
        ),
    ]
