# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170113_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksa',
            name='opis_vipoln',
            field=models.TextField(max_length=2000, verbose_name='Что должен указать исполнитель для проверки выполнения задания'),
        ),
        migrations.AlterField(
            model_name='tasksusers',
            name='opis_vipoln',
            field=models.CharField(max_length=1000, verbose_name='Ответ задания'),
        ),
    ]
