# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170113_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksusers',
            old_name='opis_vipoln',
            new_name='us_opis_vipoln',
        ),
        migrations.AlterModelTable(
            name='tasksusers',
            table='task_users',
        ),
    ]
