# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20170113_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksusers',
            name='odobren',
            field=models.BooleanField(default=False, verbose_name='Одобраить'),
        ),
        migrations.AlterField(
            model_name='tasksusers',
            name='us_opis_vipoln',
            field=models.TextField(max_length=1000, verbose_name='Ответ задания'),
        ),
    ]
