# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20170114_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksusers',
            name='odobren',
            field=models.BooleanField(default=False, verbose_name='Одобрить'),
        ),
    ]
