# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tasksusers_otvet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksusers',
            name='otvet_user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
