# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20170116_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksusers',
            old_name='otvet_user_id',
            new_name='otvet_user',
        ),
    ]
