# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20170116_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksa',
            name='price_task',
            field=models.FloatField(default=10.0, verbose_name='Укажите сумму баланса задания'),
        ),
        migrations.AlterField(
            model_name='tasksusers',
            name='otvet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
