# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20170116_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksa',
            name='pravila',
            field=models.BooleanField(default=True, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE'),
        ),
    ]
