# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tasksusers_start_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksusers',
            name='start_task',
            field=models.DateTimeField(default=0, verbose_name='Время на выполнерия'),
        ),
    ]
