# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20170118_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksusers',
            name='start_task',
            field=models.DateTimeField(verbose_name='Время на выполнерия'),
        ),
    ]
