# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balanssite', '0003_auto_20170118_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balans',
            options={'verbose_name': 'Баланс сайта', 'verbose_name_plural': 'Баланс сайта'},
        ),
    ]
