# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contlinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сайта (включая http://)')),
                ('title', models.CharField(max_length=28, verbose_name='Загаловок ссылки')),
                ('opis', models.CharField(max_length=50, verbose_name='Описание ссылки')),
                ('click', models.IntegerField(default=100, verbose_name='Количество кликов')),
                ('price_link', models.IntegerField(default=0, verbose_name='Укажите сумму баланса ссылки')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('pravila', models.BooleanField(default=True, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE')),
                ('com', models.CharField(blank=True, default='', max_length=300, verbose_name='Коментарий модерации')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобраить')),
                ('pausa', models.BooleanField(default=False, verbose_name='Пауза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Контекстная реклама',
                'verbose_name': 'Контекстная реклама',
                'db_table': 'context_links',
            },
        ),
        migrations.CreateModel(
            name='Perehod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Загаловок ссылки')),
                ('opisan', models.CharField(max_length=60, verbose_name='Краткое описание ссылки')),
                ('url', models.URLField(blank=True, verbose_name='URL сайта (включая http://)')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('price', models.CharField(choices=[('0.026', '0.026'), ('0.029', '0.029'), ('0.032', '0.032'), ('0.035', '0.035'), ('0.038', '0.038'), ('0.041', '0.041'), ('0.044', '0.044'), ('0.047', '0.047'), ('0.05', '0.05'), ('0.053', '0.053'), ('0.056', '0.056'), ('0.059', '0.059'), ('0.062', '0.062'), ('0.065', '0.065'), ('0.068', '0.068'), ('0.071', '0.071'), ('0.074', '0.074'), ('0.077', '0.077'), ('0.08', '0.08'), ('0.083', '0.083'), ('0.086', '0.086'), ('0.089', '0.089'), ('0.092', '0.092'), ('0.095', '0.095'), ('0.098', '0.098'), ('0.101', '0.101'), ('0.104', '0.104'), ('0.107', '0.107'), ('0.11', '0.11')], default='Выбор', max_length=30, verbose_name='Цена за клик:')),
                ('price_serf', models.FloatField(default=0, verbose_name='Укажите сумму баланса ссылки')),
                ('time_r', models.CharField(choices=[('5', '5 секунд (-45%)'), ('10', '10 секунд  (-30%)'), ('15', '15 секунд  (-15%)'), ('20', '20 секунд'), ('25', '25 секунд (+15%)'), ('30', '30 секунд (+30%)'), ('35', '35 секунд (+45%)'), ('40', '40 секунд (+60%)'), ('45', '45 секунд (+75%)'), ('50', '50 секунд (+90%)'), ('55', '55 секунд (+105%)'), ('60', '60 секунд (+120%)')], default='Выбор', max_length=30, verbose_name='Время просмотра ссылки')),
                ('price_u', models.FloatField(default=0, verbose_name='Вознограждение пользователю')),
                ('price_s', models.FloatField(default=0, verbose_name='Вознограждение сайту')),
                ('price_t', models.FloatField(default=0, verbose_name='Списание с баланса')),
                ('perehod', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да (+ 0,02 руб.)')], default='Выбор', max_length=10, verbose_name='Последующий переход на сайт')),
                ('porating', models.CharField(choices=[('VSEPOL', 'Все пользователи'), ('FIVE_R', 'От 5 баллов и выше (+ 0,02 руб.)'), ('TEN_R', 'От 10 баллов и выше (+ 0,02 руб.)'), ('TWENTY_R', 'От 20 баллов и выше (+ 0,02 руб.)'), ('FIVETY_R', 'От 50 баллов и выше (+ 0,02 руб.)'), ('ONEH_R', 'От 100 баллов и выше (+ 0,02 руб.)'), ('THREEH_R', 'От 300 баллов и выше (+ 0,02 руб.)'), ('FIVEH_R', 'От 500 баллов и выше (+ 0,02 руб.)')], default='Выбор', max_length=10, verbose_name='По рейтингу серфера')),
                ('posex', models.CharField(choices=[('VSEPOLZ', 'Все пользователи'), ('MEN_SEX', 'Мужчина (+ 0,01 руб.)'), ('WOOMEN_SEX', 'Женщина (+ 0,01 руб.)')], default='Выбор', max_length=10, verbose_name='По половому признаку')),
                ('pravila', models.BooleanField(default=True, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE')),
                ('prosm', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('prosm_ost', models.IntegerField(default=0, verbose_name='Количество просмотров осталось')),
                ('spis', models.BooleanField(default=False, verbose_name='Списание с 11р.')),
                ('sum_spis', models.IntegerField(default=0, verbose_name='Сумма для списания')),
                ('com', models.CharField(blank=True, default='', max_length=300, verbose_name='Коментарий модерации')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобраить')),
                ('pausa', models.BooleanField(default=False, verbose_name='Пауза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Переходы на сайты',
                'verbose_name': 'Переход на сайт',
                'db_table': 'perehod',
            },
        ),
        migrations.CreateModel(
            name='PerehodUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобрить')),
                ('pub_date', models.DateTimeField(default=0, verbose_name='Дата выполнения')),
                ('perehod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serfing.Perehod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perehod_users',
            },
        ),
        migrations.CreateModel(
            name='Pismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Заголовок письма')),
                ('opis', models.TextField(max_length=3000, verbose_name='Содержание письма')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('quest_1', models.CharField(max_length=300, verbose_name='Контрольный вопрос к письму')),
                ('quest_1_ans_1', models.CharField(max_length=30, verbose_name='Вариант ответа №1')),
                ('quest_1_ans_2', models.CharField(max_length=30, verbose_name='Вариант ответа №2')),
                ('quest_1_ans_3', models.CharField(max_length=30, verbose_name='Вариант ответа №3')),
                ('var_one', models.IntegerField(default=1, verbose_name='Укажите номер правильного ответа на вопрос')),
                ('url', models.URLField(verbose_name='URL сайта (включая http://)')),
                ('tech', models.CharField(choices=[('24_h', 'Доставляется всеи каждые 24 часа'), ('1_m', 'Доставляется всеи 1 раз в месяц (+ 0,02 руб.)')], default='Выбор', max_length=30, verbose_name='Технология доставки письма:')),
                ('time', models.CharField(choices=[('20', '20 секунд'), ('30', '30 секунд ( + 0.004 руб.)'), ('40', '40 секунд ( + 0.008 руб.)'), ('50', '50 секунд ( + 0.012 руб.)'), ('60', '60 секунд ( + 0.016 руб.)')], default='Выбор', max_length=30, verbose_name='Время просмотра ссылки')),
                ('vid', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да (+ 0,01 руб.)')], default='Выбор', max_length=10, verbose_name='Выделить письмо')),
                ('perehod', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да (+ 0,015 руб.)')], default='Выбор', max_length=10, verbose_name='Последующий переход на сайт')),
                ('porating', models.CharField(choices=[('VSEPOL', 'Все пользователи'), ('FIVE_R', 'От 5 баллов и выше (+ 0,02 руб.)'), ('TEN_R', 'От 10 баллов и выше (+ 0,02 руб.)'), ('TWENTY_R', 'От 20 баллов и выше (+ 0,02 руб.)'), ('FIVETY_R', 'От 50 баллов и выше (+ 0,02 руб.)'), ('ONEH_R', 'От 100 баллов и выше (+ 0,02 руб.)'), ('THREEH_R', 'От 300 баллов и выше (+ 0,02 руб.)'), ('FIVEH_R', 'От 500 баллов и выше (+ 0,02 руб.)')], default='Выбор', max_length=10, verbose_name='По рейтингу серфера')),
                ('posex', models.CharField(choices=[('VSEPOLZ', 'Все пользователи'), ('MEN_SEX', 'Мужчина (+ 0,01 руб.)'), ('WOOMEN_SEX', 'Женщина (+ 0,01 руб.)')], default='Выбор', max_length=10, verbose_name='По половому признаку')),
                ('price', models.FloatField(default=0.09, max_length=30, verbose_name='Цена просмотра:')),
                ('price_pismo', models.FloatField(default=0, verbose_name='Сумму баланса письма')),
                ('price_u', models.FloatField(default=0, verbose_name='Вознограждение пользователю')),
                ('price_s', models.FloatField(default=0, verbose_name='Вознограждение сайту')),
                ('price_t', models.FloatField(default=0, verbose_name='Списание с баланса')),
                ('pravila', models.BooleanField(default=True, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE')),
                ('prosm', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('prosm_ost', models.IntegerField(default=0, verbose_name='Количество просмотров осталось')),
                ('spis', models.BooleanField(default=False, verbose_name='Списание с 11р.')),
                ('sum_spis', models.IntegerField(default=0, verbose_name='Сумма для списания')),
                ('com', models.CharField(blank=True, default='', max_length=300, verbose_name='Коментарий модерации')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобраить')),
                ('pausa', models.BooleanField(default=False, verbose_name='Пауза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Чтение писем',
                'verbose_name': 'Чтение писем',
                'db_table': 'pisma',
            },
        ),
        migrations.CreateModel(
            name='PismoUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otvet', models.CharField(max_length=5, verbose_name='Ответ')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобрить')),
                ('pub_date', models.DateTimeField(default=0, verbose_name='Дата выполнения')),
                ('pismo_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serfing.Pismo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pismo_users',
            },
        ),
        migrations.CreateModel(
            name='Plinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL сайта (включая http://)')),
                ('title', models.CharField(max_length=50, verbose_name='Загаловок ссылки')),
                ('opis', models.CharField(max_length=50, verbose_name='Описание ссылки')),
                ('days', models.IntegerField(default=1, verbose_name='Количество дней')),
                ('price_link', models.IntegerField(default=0, verbose_name='Укажите сумму баланса ссылки')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('pravila', models.BooleanField(default=True, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE')),
                ('com', models.CharField(blank=True, default='', max_length=300, verbose_name='Коментарий модерации')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобраить')),
                ('pausa', models.BooleanField(default=False, verbose_name='Пауза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Псевдо ссылки',
                'verbose_name': 'Псевдо ссылка',
                'db_table': 'pseudo_links',
            },
        ),
        migrations.CreateModel(
            name='Serf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Загаловок ссылки')),
                ('opisan', models.CharField(max_length=60, verbose_name='Краткое описание ссылки')),
                ('url', models.URLField(blank=True, verbose_name='URL сайта (включая http://)')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('price', models.CharField(choices=[('0.026', '0.026'), ('0.029', '0.029'), ('0.032', '0.032'), ('0.035', '0.035'), ('0.038', '0.038'), ('0.041', '0.041'), ('0.044', '0.044'), ('0.047', '0.047'), ('0.05', '0.05'), ('0.053', '0.053'), ('0.056', '0.056'), ('0.059', '0.059'), ('0.062', '0.062'), ('0.065', '0.065'), ('0.068', '0.068'), ('0.071', '0.071'), ('0.074', '0.074'), ('0.077', '0.077'), ('0.08', '0.08'), ('0.083', '0.083'), ('0.086', '0.086'), ('0.089', '0.089'), ('0.092', '0.092'), ('0.095', '0.095'), ('0.098', '0.098'), ('0.101', '0.101'), ('0.104', '0.104'), ('0.107', '0.107'), ('0.11', '0.11')], default='Выбор', max_length=30, verbose_name='Цена за клик:')),
                ('price_serf', models.FloatField(default=0, verbose_name='Укажите сумму баланса ссылки')),
                ('time_r', models.CharField(choices=[('5', '5 секунд (-45%)'), ('10', '10 секунд  (-30%)'), ('15', '15 секунд  (-15%)'), ('20', '20 секунд'), ('25', '25 секунд (+15%)'), ('30', '30 секунд (+30%)'), ('35', '35 секунд (+45%)'), ('40', '40 секунд (+60%)'), ('45', '45 секунд (+75%)'), ('50', '50 секунд (+90%)'), ('55', '55 секунд (+105%)'), ('60', '60 секунд (+120%)')], default='Выбор', max_length=30, verbose_name='Время просмотра ссылки')),
                ('price_u', models.FloatField(default=0, verbose_name='Вознограждение пользователю')),
                ('price_s', models.FloatField(default=0, verbose_name='Вознограждение сайту')),
                ('price_t', models.FloatField(default=0, verbose_name='Списание с баланса')),
                ('perehod', models.CharField(choices=[('NO', 'Нет'), ('YES', 'Да (+ 0,02 руб.)')], default='Выбор', max_length=10, verbose_name='Последующий переход на сайт')),
                ('porating', models.CharField(choices=[('VSEPOL', 'Все пользователи'), ('FIVE_R', 'От 5 баллов и выше (+ 0,02 руб.)'), ('TEN_R', 'От 10 баллов и выше (+ 0,02 руб.)'), ('TWENTY_R', 'От 20 баллов и выше (+ 0,02 руб.)'), ('FIVETY_R', 'От 50 баллов и выше (+ 0,02 руб.)'), ('ONEH_R', 'От 100 баллов и выше (+ 0,02 руб.)'), ('THREEH_R', 'От 300 баллов и выше (+ 0,02 руб.)'), ('FIVEH_R', 'От 500 баллов и выше (+ 0,02 руб.)')], default='Выбор', max_length=10, verbose_name='По рейтингу серфера')),
                ('posex', models.CharField(choices=[('VSEPOLZ', 'Все пользователи'), ('MEN_SEX', 'Мужчина (+ 0,01 руб.)'), ('WOOMEN_SEX', 'Женщина (+ 0,01 руб.)')], default='Выбор', max_length=10, verbose_name='По половому признаку')),
                ('pravila', models.BooleanField(default=True, verbose_name='Я согласен(на) с правилами размещения рекламы на WMR_LOVE')),
                ('prosm', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('prosm_ost', models.IntegerField(default=0, verbose_name='Количество просмотров осталось')),
                ('spis', models.BooleanField(default=False, verbose_name='Списание с 11р.')),
                ('sum_spis', models.IntegerField(default=0, verbose_name='Сумма для списания')),
                ('com', models.CharField(blank=True, default='', max_length=300, verbose_name='Коментарий модерации')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобраить')),
                ('pausa', models.BooleanField(default=False, verbose_name='Пауза')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Серфинг сайтов',
                'verbose_name': 'Серфинг сайта',
                'db_table': 'serf',
            },
        ),
        migrations.CreateModel(
            name='SerfUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odobren', models.BooleanField(default=False, verbose_name='Одобрить')),
                ('pub_date', models.DateTimeField(default=0, verbose_name='Дата выполнения')),
                ('serf_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serfing.Serf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'serf_users',
            },
        ),
    ]
