# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Тема')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('recipient', models.CharField(max_length=50, verbose_name='Кому')),
                ('read', models.BooleanField(default=False, verbose_name='Прочитан')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('delete_one', models.BooleanField(default=False, verbose_name='Удален отправителем')),
                ('delete_two', models.BooleanField(default=False, verbose_name='Удален получателем')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profuser.UserInfo', verbose_name='От кого')),
            ],
            options={
                'verbose_name': 'Личное сообщение',
                'verbose_name_plural': 'Личные сообщения',
                'db_table': 'my_mail',
            },
        ),
    ]
